/**
 * Technology name → icon path (without extension), relative to public/assets/skills/.
 * Must match an actual public/assets/skills/<group>/<name>.svg exactly.
 */
const TECH_ICON_MAP: Record<string, string> = {
  "next.js": "framework/nextjs",
  nextjs: "framework/nextjs",
  react: "framework/react",
  "react.js": "framework/react",
  reactjs: "framework/react",
  "react three fiber": "framework/react",
  typescript: "languages/typescript",
  ts: "languages/typescript",
  javascript: "languages/javascript",
  js: "languages/javascript",
  "node.js": "framework/nodejs",
  nodejs: "framework/nodejs",
  express: "framework/express",
  "express.js": "framework/express",
  tailwind: "framework/tailwindcss",
  "tailwind css": "framework/tailwindcss",
  tailwindcss: "framework/tailwindcss",
  postgresql: "database/postgresql",
  mongodb: "database/mongodb",
  firebase: "database/firebase",
  supabase: "database/supabase",
  flutter: "framework/flutter",
  expo: "framework/expo",
  dart: "languages/dart",
  aws: "database/aws",
  vercel: "database/vercel",
  docker: "database/docker",
  render: "database/render",
  vite: "framework/vite",
  html: "languages/html",
  css: "languages/css",
  java: "languages/java",
  php: "languages/php",
  laravel: "framework/laravel",
  leegality: "framework/leegality",
  shadcn: "framework/shadcn",
  "shadcn/ui": "framework/shadcn",
  "shadcn ui": "framework/shadcn",
  getx: "stateManagement/getx",
  bloc: "stateManagement/bloc",
  "redux toolkit": "stateManagement/redux-toolkit",
  "redux-toolkit": "stateManagement/redux-toolkit",
  zustand: "stateManagement/zustand",
  "react router": "framework/react-router",
  "react-router": "framework/react-router",
  mysql: "database/mysql",
  git: "serviceTools/git",
  figma: "serviceTools/figma",
  stripe: "serviceTools/stripe",
  razorpay: "serviceTools/razorpay",
  postman: "serviceTools/postman",
  openai: "serviceTools/openai",
  anthropic: "serviceTools/anthropic",
  android: "serviceTools/android",
  apple: "serviceTools/apple",
  "app store": "serviceTools/appstore",
  "play store": "serviceTools/playstore",
  "vs code": "serviceTools/vscode",
  vscode: "serviceTools/vscode",
  "google ai": "serviceTools/googleai",
  "google analytics": "serviceTools/googleanalytics",
  "google ads": "serviceTools/googleads",
  "google maps": "serviceTools/googlemaps",
  meta: "serviceTools/meta",
  interakt: "serviceTools/interakt",
  pabbly: "serviceTools/pabbly",
  "pabbly connect": "serviceTools/pabbly",
  zegocloud: "serviceTools/zegocloud",
  agora: "serviceTools/agora",
  tensorflow: "serviceTools/tensorflow",
  tflite: "serviceTools/tensorflow",
  framer: "framework/framer",
  "framer motion": "framework/framer",
  c: "languages/c",
  clerk: "serviceTools/clerk",
  "claude code": "serviceTools/claude-code",
  cursor: "serviceTools/cursor",
  "desktop development": "serviceTools/desktop-development",
  "local storage": "serviceTools/local-storage",
  "microsoft clarity": "serviceTools/microsoft-clarity",
  revenuecat: "serviceTools/revenuecat",
  "website development": "serviceTools/website-development",
  websocket: "serviceTools/websocket",
  hostinger: "serviceTools/hostinger",
};

export function getTechIcon(techName: string): string | null {
  return TECH_ICON_MAP[techName.toLowerCase().trim()] ?? null;
}

export function getTechIconPath(techName: string): string | null {
  const icon = getTechIcon(techName);
  return icon ? `/assets/skills/${icon}.svg` : null;
}
